#3307: The port on your host machine that you will use to access MySQL.
#3306: The port inside the container where MySQL is running.

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql




